language: node_js
node_js:
- stable
notifications:
  slack:
    secure: wC6FOv69Am7yem/IUrw/r0QEDbJVVBMZberPW4nNtQYOTkqCmYPxMb1aUW/1CqT0fxpKhdOkjbVTdrBbrIgEyRpovsEF73CxEnTcZ0wf9x87J0jmLB99grUGMpwnZh4VlVVBsqeeLoW5AWOuJVskiZ5zJWUyh91DaE0q4F697lHOxMOHoigiN6TowfnpN2LiquleB5DnuQeYd5ExiyP3uHR6+Ia+eZeyCYplwnJLRS1zFwZze+WwlyrJxfKzFMNB3CDxo/ymcBxYMG3i+uwFn+3/Y0Sb//BW9Gil8xM+3zTBe4dkVh7fPCd5WKOIRUIknT8HWXDxRwyJU1JfOBhijeWCNUsAR70lQiVTAwhXCgYTkRQBgyxRonsrpHLDi4R4V4AC/dpiU/AT+Rxn5+BmEoNTxywFa9tWNkj+gI/5yUSbY0VIdaqooTuGY2YP9caMR7YQbqdMndmERR9ajGJlpwI/eQN7jaRstD3ADYjAqZtdvmHO7EuDfHV8Hc9n0hPFTiNd4LLo1Kew0VqoqwTL/ZU/984bWRdOnj2phczX40SwUFQihj1056KQ4ihQwm2ZUyCKhhAkWPtQfRjLbqqwRXsqG1rndYaXRFfxNRanWZkmFlv2cku6UXdBsLvHmqWbTPEj5tsXeH0fvLY75vVZPnL+byH95Llm0/0/fqnnQfY=
